Install-Module ExchangeOnlineManagement
Import-Module ExchangeOnlineManagement

Connect-ExchangeOnline -UserPrincipalName navin@contoso.onmicrosoft.com
Connect-ExchangeOnline -UserPrincipalName josh.golosinskiy@autobidmaster.com